package com.jash.himalayademo.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FOCUS_IMAGE_ENTITY".
 */
public class FocusImageEntity {

    private Long id;
    private String shortTitle;
    private String longTitle;
    private String pic;
    private Integer type;
    private Integer specialId;
    private Integer subType;
    private Boolean isShare;
    private Boolean is_External_url;

    public FocusImageEntity() {
    }

    public FocusImageEntity(Long id) {
        this.id = id;
    }

    public FocusImageEntity(Long id, String shortTitle, String longTitle, String pic, Integer type, Integer specialId, Integer subType, Boolean isShare, Boolean is_External_url) {
        this.id = id;
        this.shortTitle = shortTitle;
        this.longTitle = longTitle;
        this.pic = pic;
        this.type = type;
        this.specialId = specialId;
        this.subType = subType;
        this.isShare = isShare;
        this.is_External_url = is_External_url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getShortTitle() {
        return shortTitle;
    }

    public void setShortTitle(String shortTitle) {
        this.shortTitle = shortTitle;
    }

    public String getLongTitle() {
        return longTitle;
    }

    public void setLongTitle(String longTitle) {
        this.longTitle = longTitle;
    }

    public String getPic() {
        return pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getSpecialId() {
        return specialId;
    }

    public void setSpecialId(Integer specialId) {
        this.specialId = specialId;
    }

    public Integer getSubType() {
        return subType;
    }

    public void setSubType(Integer subType) {
        this.subType = subType;
    }

    public Boolean getIsShare() {
        return isShare;
    }

    public void setIsShare(Boolean isShare) {
        this.isShare = isShare;
    }

    public Boolean getIs_External_url() {
        return is_External_url;
    }

    public void setIs_External_url(Boolean is_External_url) {
        this.is_External_url = is_External_url;
    }

}
